"""Playwright walkthrough for the demo video: 17 steps, numbered screenshots.

Steps 1-3 show the Phase-1 migration artifacts (.rdl → thought file → HTML
template) rendered as styled code viewers; steps 4-17 drive the live app.

Runs headed — the Classic/SSRS report is a PDF in an iframe and headless
Chromium has no PDF viewer. Selector/wait patterns proven in
presentation/evidence/capture_evidence.py.

Returns metadata the orchestrator needs (which narration variant step 9 uses).
"""

import html
import tempfile
from pathlib import Path

from playwright.sync_api import sync_playwright

BASE = "http://localhost:5282"
ROOT = Path(__file__).resolve().parents[1]
SCREENSHOTS = Path(__file__).parent / "screenshots"
VIEWPORT = {"width": 1280, "height": 800}
ASK_TIMEOUT = 120_000

# Candidates in preference order; the local model is non-deterministic, so we
# try each a few times and fall back to alternate narration if it keeps coping.
FALLBACK_QUESTIONS = [
    "which sheet lists the folks who got cells from a donor other than themselves",
    "pull up the sheet for the lady from the dallas clinic",
]

# Phase-1 artifact lineage shown in steps 1-3 (same report, three stages).
ARTIFACTS = [
    (ROOT / "Reports" / "GenericTransplantListReport.rdl",
     "Phase 1 — the legacy report", "SSRS Report Definition (RDL XML)"),
    (ROOT / "ReportThoughts" / "transplant_event.thought.md",
     "Phase 1 — the thought file", "Human-reviewed business-logic analysis (generated by the Claude Code plugin)"),
    (ROOT / "HTMLReportsFolder" / "transplant_event.html",
     "Phase 1 — the generated report", "Self-contained HTML template (renders from window.REPORT_DATA)"),
]

_VIEWER_CSS = """
body{margin:0;font-family:'Segoe UI',sans-serif;background:#f4f6fa}
header{background:#1f3864;color:#fff;padding:18px 28px}
header h1{margin:0;font-size:1.4rem} header p{margin:4px 0 0;color:#c7d4ee;font-size:.95rem}
.path{background:#dbe5f1;color:#1f3864;padding:6px 28px;font-family:Consolas,monospace;font-size:.85rem}
pre{margin:0;padding:20px 28px;font-family:Consolas,monospace;font-size:.78rem;line-height:1.45;
    color:#1b2330;background:#fff;white-space:pre-wrap;word-break:break-all}
"""


def artifact_viewer(src: Path, title: str, subtitle: str, max_lines: int = 46) -> str:
    """Write a styled, escaped code-viewer page for an artifact; return file:// URL."""
    lines = src.read_text(encoding="utf-8", errors="replace").splitlines()
    body = "\n".join(lines[:max_lines])
    if len(lines) > max_lines:
        body += f"\n… ({len(lines) - max_lines} more lines)"
    page = (f"<!doctype html><html><head><meta charset='utf-8'><style>{_VIEWER_CSS}</style></head>"
            f"<body><header><h1>{html.escape(title)}</h1><p>{html.escape(subtitle)}</p></header>"
            f"<div class='path'>{html.escape(str(src.relative_to(ROOT)))}</div>"
            f"<pre>{html.escape(body)}</pre></body></html>")
    out = Path(tempfile.gettempdir()) / f"artifact-{src.stem}.html"
    out.write_text(page, encoding="utf-8")
    return out.as_uri()


def ask(page, question: str, button_id: str) -> None:
    page.goto(f"{BASE}/Reports/HtmlReports")
    page.fill("#question", question)
    page.click(f"#{button_id}")
    # Ask navigates back to the hub at the ROOT url (default route) — wait for
    # the provenance/error banner, not a URL.
    page.wait_for_selector("div.alert", timeout=ASK_TIMEOUT)


def banner_text(page) -> str:
    return page.locator("div.alert").first.inner_text()


def wait_report_iframe(page) -> None:
    frame = page.frame_locator('iframe[title="HTML report"]')
    frame.locator("table").first.wait_for(timeout=60_000)
    page.wait_for_timeout(2_000)  # let /summarize land in the prompt log


def shot(page, name: str) -> None:
    SCREENSHOTS.mkdir(exist_ok=True)
    page.screenshot(path=str(SCREENSHOTS / f"{name}.png"))
    print(f"  captured {name}.png")


def run() -> dict:
    """Returns {'fallback_variant': 'step-09' | 'step-09-alt'}."""
    meta = {"fallback_variant": "step-09"}
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=False)
        page = browser.new_page(viewport=VIEWPORT)

        for i, (src, title, subtitle) in enumerate(ARTIFACTS, start=1):
            print(f"step {i}: artifact — {src.name}")
            page.goto(artifact_viewer(src, title, subtitle))
            shot(page, f"step-{i:02d}")

        print("step 4: landing page")
        page.goto(f"{BASE}/Reports/HtmlReports")
        page.wait_for_selector("#question")
        shot(page, "step-04")

        print("step 5: question typed")
        page.fill("#question", "Show me patients at Austin General")
        shot(page, "step-05")

        print("step 6: ask local AI")
        page.click("#askBtn")
        page.wait_for_selector("div.alert", timeout=ASK_TIMEOUT)
        wait_report_iframe(page)
        shot(page, "step-06")

        print("step 7: AI summary in view")
        page.frame_locator('iframe[title="HTML report"]').locator("table").first.scroll_into_view_if_needed()
        page.wait_for_timeout(500)
        shot(page, "step-07")

        print("step 8: ask Claude")
        ask(page, "Show female patients at Austin General Hospital", "askClaudeBtn")
        wait_report_iframe(page)
        shot(page, "step-08")

        print("step 9: automatic fallback (up to 3 attempts per candidate prompt)")
        got_fallback = False
        for question in FALLBACK_QUESTIONS:
            for attempt in range(3):
                ask(page, question, "askBtn")
                if "fallback" in banner_text(page).lower():
                    got_fallback = True
                    break
                print(f"  local model decoded it (attempt {attempt + 1}) — retrying")
            if got_fallback:
                break
        if not got_fallback:
            meta["fallback_variant"] = "step-09-alt"
            print("  fallback did not trigger — using alternate narration")
        wait_report_iframe(page)
        shot(page, "step-09")

        print("step 10: MRN fail-closed")
        ask(page, "show patient with MRN-00003", "askBtn")
        wait_report_iframe(page)
        shot(page, "step-10")

        print("step 11: prompt log routing")
        page.goto(f"{BASE}/Reports/PromptLog")
        page.wait_for_selector("#promptLogAccordion .accordion-item", timeout=15_000)
        shot(page, "step-11")

        print("step 12: PHI before/after")
        groups = page.locator("#promptLogAccordion .accordion-item")
        for i in range(groups.count()):
            g = groups.nth(i)
            if "Austin General" in g.locator(".accordion-button").inner_text():
                g.locator(".accordion-button").click()
                break
        page.wait_for_timeout(800)
        before = page.locator(".accordion-collapse.show div.border-danger-subtle").first
        before.wait_for(timeout=10_000)
        before.scroll_into_view_if_needed()
        shot(page, "step-12")

        print("step 13: dropdown selection")
        page.goto(f"{BASE}/Reports/HtmlReports")
        page.select_option("#report", "transplant")
        shot(page, "step-13")

        print("step 14: transplant report via dropdown")
        # NB: the dropdown form's action renders as the ROOT url (default
        # route), so don't select by form action.
        page.click('button:has-text("Generate Report")')
        page.wait_for_selector('iframe[title="HTML report"]', timeout=30_000)
        page.frame_locator('iframe[title="HTML report"]').locator("table").first.wait_for(timeout=30_000)
        shot(page, "step-14")

        print("step 15: clinical summary")
        page.select_option("#report", "clinical")
        page.click('button:has-text("Generate Report")')
        page.wait_for_selector('iframe[title="HTML report"]', timeout=30_000)
        page.frame_locator('iframe[title="HTML report"]').locator("table").first.wait_for(timeout=60_000)
        shot(page, "step-15")

        print("step 16: classic SSRS page")
        page.click('a.nav-link:has-text("Classic Reports")')
        page.wait_for_selector("#report")
        shot(page, "step-16")

        print("step 17: SSRS report rendered")
        page.select_option("#report", "patient")
        page.click("button.btn-primary")
        page.wait_for_selector("#rdlFrame", timeout=30_000)
        page.wait_for_timeout(8_000)  # PDF render inside the iframe
        shot(page, "step-17")

        browser.close()
    return meta


if __name__ == "__main__":
    print(run())
